list = []
print("===========================================")
print(list)
print("===========================================")
list.append(12)
list.append("Fast University")
list.append(34.67)
list.append("^&*$")
list.append("qwerty")
print("===========================================")
print(list)
print("===========================================")
list.extend([23,45,"qwerty"])
print(list)
